import "./globals.css";
import Header from "@/components/layouts/Header";
import { GlobalProvider } from "./GlobalProvider";
import "./globals.css";
import { AuthDebugger } from "@/components/auth/auth-check";

export const metadata = {
  title: "Web Plaza",
  description: "Generated by IBassemTarek",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head />
      <body suppressHydrationWarning={true}>
        <GlobalProvider>
          <Header />
          {children}
          <AuthDebugger />
        </GlobalProvider>
      </body>
    </html>
  );
}
